name: Android Emulator Screenshot & Connected Check

on:
  push:
    branches: [ master ]

jobs:
  emulator-screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Enable KVM on runner
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Create minimal Android app source and test files
        run: |
          # --- Set up basic Android project structure ---
          mkdir -p app/src/main/java/com/example/helloworld
          mkdir -p app/src/main/res/layout
          mkdir -p app/src/main/res/values
          mkdir -p app/src/main/res/mipmap
          mkdir -p app/src/androidTest/java/com/example/helloworld

          # --- Create Gradle configuration files ---
          echo "android.useAndroidX=true" > gradle.properties
          cat > settings.gradle <<EOF
          rootProject.name = "HelloWorld"
          include ':app'
          EOF
          cat > build.gradle <<EOF
          buildscript {
              repositories {
                  google()
                  mavenCentral()
              }
              dependencies {
                  classpath 'com.android.tools.build:gradle:8.1.3'
              }
          }
          allprojects {
              repositories {
                  google()
                  mavenCentral()
              }
          }
          EOF

          # --- Create app-level build.gradle with dependencies and test runner ---
          cat > app/build.gradle <<EOF
          plugins {
              id 'com.android.application'
          }
          android {
              namespace 'com.example.helloworld'
              compileSdk 33
              defaultConfig {
                  applicationId "com.example.helloworld"
                  minSdk 21
                  targetSdk 33
                  versionCode 1
                  versionName "1.0"
                  testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
              }
              buildTypes {
                  release {
                      minifyEnabled false
                      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
                  }
              }
              testOptions {
                  animationsDisabled = true  // Disable animations for faster testing
                  resultsDir = System.getenv("GITHUB_WORKSPACE") + "/test-results"  // Store test results in workspace
                  reportDir = System.getenv("GITHUB_WORKSPACE") + "/test-reports"  // Store test reports in workspace
              }
              // Configure screenshot directory for tests
              defaultConfig {
                  testInstrumentationRunnerArguments["screenshotDir"] = System.getenv("GITHUB_WORKSPACE") + "/screenshots"
              }
          }
          dependencies {
              implementation 'androidx.appcompat:appcompat:1.6.1'
              implementation 'com.google.android.material:material:1.9.0'
              testImplementation 'junit:junit:4.13.2'
              androidTestImplementation 'androidx.test.ext:junit:1.1.5'
              androidTestImplementation 'androidx.test.uiautomator:uiautomator:2.2.0'
              androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
              androidTestImplementation 'androidx.test:runner:1.5.2'
              androidTestImplementation 'androidx.test:rules:1.5.0'
              androidTestImplementation 'androidx.test:core:1.5.0'
              androidTestImplementation 'junit:junit:4.13.2'
          }
          EOF

          # --- Create AndroidManifest.xml ---
          cat > app/src/main/AndroidManifest.xml <<EOF
          <manifest xmlns:android="http://schemas.android.com/apk/res/android"
                package="com.example.helloworld">
               <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
               <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
               <uses-permission android:name="android.permission.MOUNT_UNMOUNT_FILESYSTEMS"/>
              <application
                  android:allowBackup="true"
                  android:icon="@mipmap/ic_launcher"
                  android:label="@string/app_name"
                  android:roundIcon="@mipmap/ic_launcher_round"
                  android:supportsRtl="true"
                  android:theme="@style/AppTheme"> <activity
                      android:name=".MainActivity"
                      android:exported="true">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" />
                          <category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
                  </activity>
              </application>
          </manifest>
          EOF

          # --- Create MainActivity.java (corrected: removed 'import R.layout;') ---
          cat > app/src/main/java/com/example/helloworld/MainActivity.java <<EOF
          package com.example.helloworld;
          import android.os.Bundle;
          import androidx.appcompat.app.AppCompatActivity;
          public class MainActivity extends AppCompatActivity {
              @Override
              protected void onCreate(Bundle savedInstanceState) {
                  super.onCreate(savedInstanceState);
                  setContentView(R.layout.activity_main);
              }
          }
          EOF

          # --- Create activity_main.xml layout ---
          cat > app/src/main/res/layout/activity_main.xml <<EOF
          <?xml version="1.0" encoding="utf-8"?>
          <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:orientation="vertical"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:gravity="center">
              <TextView
                  android:id="@+id/hello"
                  android:layout_width="wrap_content"
                  android:layout_height="wrap_content"
                  android:text="Hello World from Actions!"
                  android:textSize="24sp"/>
          </LinearLayout>
          EOF

          # --- Create strings.xml ---
          cat > app/src/main/res/values/strings.xml <<EOF
          <resources>
              <string name="app_name">HelloWorld</string>
          </resources>
          EOF

          # --- Create styles.xml (corrected: proper AppTheme definition) ---
          cat > app/src/main/res/values/styles.xml <<EOF
          <resources>
              <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar" />
          </resources>
          EOF

          # --- Create mipmap icons ---
          cat > app/src/main/res/mipmap/ic_launcher.xml <<EOF
          <vector xmlns:android="http://schemas.android.com/apk/res/android"
              android:width="48dp"
              android:height="48dp"
              android:viewportWidth="48"
              android:viewportHeight="48">
              <path android:fillColor="#3DDC84" android:pathData="M0,0h48v48h-48z"/>
              <path android:fillColor="#FFF" android:pathData="M24,8a16,16 0 1,0 0,32a16,16 0 1,0 0,-32z"/>
          </vector>
          EOF

          cat > app/src/main/res/mipmap/ic_launcher_round.xml <<EOF
          <vector xmlns:android="http://schemas.android.com/apk/res/android"
              android:width="48dp"
              android:height="48dp"
              android:viewportWidth="48"
              android:viewportHeight="48">
              <path android:fillColor="#3DDC84" android:pathData="M24,4a20,20 0 1,0 0,40a20,20 0 1,0 0,-40z"/>
              <path android:fillColor="#FFF" android:pathData="M24,12a12,12 0 1,0 0,24a12,12 0 1,0 0,-24z"/>
          </vector>
          EOF

          cat > app/proguard-rules.pro <<EOF
          # No rules
          EOF

          # --- Create ExampleInstrumentedTest.java for connectedCheck ---
          cat > app/src/androidTest/java/com/example/helloworld/ExampleInstrumentedTest.java <<EOF
            package com.example.helloworld;

            import android.content.Context;
            import android.graphics.Bitmap;
            import android.os.Environment;
            import androidx.test.platform.app.InstrumentationRegistry;
            import androidx.test.ext.junit.runners.AndroidJUnit4;
            import androidx.test.espresso.Espresso;
            import androidx.test.espresso.matcher.ViewMatchers;
            import androidx.test.espresso.assertion.ViewAssertions;
            import androidx.test.rule.ActivityTestRule;
            import androidx.test.uiautomator.UiDevice;
            import org.junit.Rule;
            import org.junit.Test;
            import org.junit.runner.RunWith;
            import java.io.File;
            import java.io.FileOutputStream;
            import java.io.IOException;

            import static org.junit.Assert.assertEquals;
            import static androidx.test.espresso.matcher.ViewMatchers.withId;
            import static androidx.test.espresso.matcher.ViewMatchers.withText;
            import static androidx.test.espresso.assertion.ViewAssertions.matches;

            import android.util.Log;

            import androidx.test.core.app.ActivityScenario;

            import android.view.View;

            import androidx.test.espresso.UiController;
            import androidx.test.espresso.ViewAction;

            import org.hamcrest.Matcher;
            import org.hamcrest.Description;
            import org.hamcrest.TypeSafeMatcher;

            import android.graphics.Canvas;

            import java.util.UUID;

            //import android.graphics.drawable.Drawable;
            //import android.support.v4.content.ContextCompat;

            import static androidx.test.espresso.Espresso.onView;
            import static androidx.test.espresso.matcher.ViewMatchers.isRoot;

            @RunWith(AndroidJUnit4.class)
            public class ExampleInstrumentedTest {

                @Rule
                public ActivityTestRule<MainActivity> activityRule =
                        new ActivityTestRule<>(MainActivity.class);

                @Test
                public void useAppContext() {
                    Context appContext = InstrumentationRegistry.getInstrumentation().getTargetContext();
                    assertEquals("com.example.helloworld", appContext.getPackageName());
                }

                @Test
                public void helloWorldTextViewIsDisplayed() {
                    Espresso.onView(withId(R.id.hello))
                            .check(matches(withText("Hello World from Actions!")));
                }

                @Test
                public void certainTextDoesNotExist() {
                    String nonExistentText = "Hello from Actions!";
                    Espresso.onView(withText(nonExistentText)).check(ViewAssertions.doesNotExist());
                }

                // ----------- Screenshot Test ----------- //
                @Test
                public void saveDeviceScreenBitmap() throws Exception {
                    String screenshotDir = InstrumentationRegistry.getInstrumentation()
                            .getTargetContext()
                            .getFilesDir()
                            .getAbsolutePath();

                    String filename = "ExampleInstrumentedTest_saveDeviceScreenBitmap.png";
                    File screenshotFile = new File(screenshotDir, filename);

                    // Using Espresso to get a root view
                    onView(isRoot()).perform(takeScreenshot(screenshotFile));

                    Log.d("ScreenshotTest", "Screenshot saved to: " + screenshotFile.getAbsolutePath());
                }

                public static ViewAction takeScreenshot(File screenshotFile) {
                    return new ViewAction() {
                        @Override
                        public Matcher<View> getConstraints() {
                            return isRoot();
                        }

                        @Override
                        public String getDescription() {
                            return "Taking a screenshot and saving it to " + screenshotFile.getAbsolutePath();
                        }

                        @Override
                        public void perform(UiController uiController, View view) {
                            uiController.loopMainThreadUntilIdle();
                            View content = activityRule.getActivity().getWindow().getDecorView().getRootView();
                            Bitmap bitmap = getBitmapFromView(content);

                            FileOutputStream fileOutputStream = null;
                            try {
                                fileOutputStream = new FileOutputStream(screenshotFile);
                                bitmap.compress(Bitmap.CompressFormat.PNG, 100, fileOutputStream);
                            } catch (IOException e) {
                                throw new RuntimeException("Failed to save screenshot to " + screenshotFile.getAbsolutePath(), e);
                            } finally {
                                if (fileOutputStream != null) {
                                    try {
                                        fileOutputStream.close();
                                    } catch (IOException e) {
                                        // Ignore
                                    }
                                }
                            }
                        }

                        private Bitmap getBitmapFromView(View view) {
                            Bitmap bitmap = Bitmap.createBitmap(view.getWidth(), view.getHeight(), Bitmap.Config.ARGB_8888);
                            Canvas canvas = new Canvas(bitmap);
                            view.draw(canvas);
                            return bitmap;
                        }
                    };
                }
            }
          EOF

      - name: Set Gradle wrapper executable
        run: |
          gradle wrapper
          chmod +x gradlew

      - name: Create Directories for Test Results and Screenshots
        run: |
          mkdir -p test-results
          mkdir -p screenshots

      - name: Run Connected Tests (gradlew connectedCheck)
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          script: |
            adb wait-for-device
            adb devices
            ./gradlew connectedCheck

      - name: Generate HTML Test Report
        run: |
          ./gradlew app:testDebugUnitTestReport
      - name: Upload HTML Test Report
        uses: actions/upload-artifact@v4
        with:
          name: html-test-report
          path: app/build/reports/tests/testDebugUnitTest/index.html
      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: app/build/intermediates/androidTest/debug/files/screenshots/

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-test-results
          path: app/build/outputs/androidTest-results/connected/*
