name: Build Android APK

on:
  push:
    branches:
      - master

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Download Android SDK Command Line Tools
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools.zip
        rm commandlinetools.zip
        mv cmdline-tools latest
      shell: bash

    - name: Set ANDROID_HOME and update PATH
      run: |
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
      shell: bash

    - name: Accept licenses and install SDK platforms and build tools
      run: |
        yes | sdkmanager --sdk_root=$HOME/android-sdk --licenses
        sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-33" "build-tools;33.0.2"
      shell: bash

    - name: Build Debug APK
      run: ./gradlew assembleDebug
      env:
        ANDROID_SDK_ROOT: $HOME/android-sdk

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
