name: Android Emulator Screenshot

on:
  # Triggers the workflow on push or pull request events but only for default and protected branches
  push:
    branches: [ master ]

jobs:
  emulator-screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Start Android Emulator and Take Screenshot
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          script: |
            sleep 10 # wait for the emulator UI to fully load
            adb exec-out screencap -p > screenshot.png

      - name: Upload Emulator Screenshot
        uses: actions/upload-artifact@v4
        with:
          name: emulator-screenshot
          path: screenshot.png